env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: 'detect'
rules:
  'no-use-before-define': off
overrides:
  files: ["**/*.tsx"],
  rules:
    "react/prop-types": off
