# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.13.x
      - name: version check
        run: node -v

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn install
      
      - name: lint
        run: yarn run eslint .

      - name: build
        run: yarn build
